# Generated by Django 2.0.3 on 2020-04-29 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='large',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='small',
        ),
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
