# Generated by Django 2.0.3 on 2020-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200430_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='main',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
