# Generated by Django 2.0.3 on 2020-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200430_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='toppings',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='main',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
