# Generated by Django 2.0.3 on 2020-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='topping1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='topping2',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
