# Generated by Django 2.0.3 on 2020-05-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200501_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additions',
        ),
    ]
