# Generated by Django 3.0.5 on 2020-04-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('main', models.CharField(max_length=64)),
                ('small', models.IntegerField()),
                ('large', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('main', models.CharField(max_length=64)),
                ('toppings', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=64)),
            ],
        ),
    ]
