# Generated by Django 3.0.5 on 2020-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menu_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='topping',
        ),
        migrations.AlterField(
            model_name='orders',
            name='toppings',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
