# Generated by Django 2.0.3 on 2020-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200428_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
