# Generated by Django 2.0.3 on 2020-04-30 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
