# Generated by Django 2.0.3 on 2020-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200430_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='addition',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
